apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.sidstarUI.name }}
  name: {{ .Values.sidstarUI.service.name }}
spec:
  ports:
  - port: {{ .Values.sidstarUI.service.port }}
    protocol: {{ .Values.sidstarUI.service.protocol }}
    targetPort: {{ .Values.sidstarUI.service.targetPort }}
    nodePort: {{ .Values.sidstarUI.service.nodePort }}
  selector:
    app: {{ .Values.sidstarUI.name }}
  type: {{ .Values.sidstarUI.service.type }}