global:
  apiKey:

sidstar:
  name: sidstar
  replicas: 1
  image:
    name: localhost:5000/sidstar-be
    pullPolicy: Always
    tag: v1
    env:
    - name: APIKEY
      valueFrom:
        secretKeyRef:
          name: sidstar-secret
          key: api-key
  service:
    name: sidstar-svc
    type: NodePort
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30009
sidstarUI:
  name: sidstar-ui
  replicas: 1
  image:
    name: localhost:5000/sidstar-fe
    pullPolicy: Always
    tag: v1
  service:
    name: sidstar-ui-svc
    type: NodePort
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30010
secret:
  name: sidstar-secret
